name: 'GitHub Branch Deployer'
description: 'This action will deploy a folder to a GitHub branch.'
author: 'Nicholas Griffin'
branding:
  icon: upload-cloud
  color: blue
inputs:
  GITHUB_TOKEN:
    description: 'Provide a GitHub token here, this is used to communicate with GitHub during the actionss processes.'
    required: true
    default: ${{ github.token }}
  REPO:
    description: 'Repository name to push to, leave this empty to use the current repo.'
    default: 'self'
    required: false
  BRANCH:
    description: 'Destination branch to push changes'
    required: true
  FOLDER:
    description: 'Directory to push from. Defaults to root'
    required: false
    default: '.'
  MESSAGE:
    description: 'Change the message thats used for the build commit'
    required: false
    default: 'Build: ({sha}) {msg}'
runs:
  using: 'node12'
  main: 'src/index.js'
